res = {
    162: {"name": "c++ function", "fontStyle": "italic underline", "pos": 2},
    183: {"name": "js/ts import keyword", "fontStyle": "underline", "pos": 2},
    256: {"name": "java variable.name", "fontStyle": "italic", "pos": 2},
    312: {"name": "css attribute-name.id", "fontStyle": "italic underline", "pos": 2},
    319: {"name": "css property-name", "fontStyle": "italic underline", "pos": 2},
    360: {"name": "js/ts Keyword", "fontStyle": "italic", "pos": 2},
    381: {"name": "js console function", "fontStyle": "italic", "pos": 2},
    416: {"name": "js dom variable", "fontStyle": "underline", "pos": 2},
    423: {"name": "keyword.operator", "fontStyle": "bold", "pos": 2},
    430: {"name": "C operator assignment", "fontStyle": "bold", "pos": 2},
    458: {"name": "keyword.operator.sizeof.c", "fontStyle": "italic", "pos": 2},
    465: {"name": "python parameter", "fontStyle": "italic", "pos": 2},
    472: {"name": "python type", "fontStyle": "italic", "pos": 2},
    479: {"name": "python logical", "fontStyle": "bold", "pos": 2},
    514: {"name": "Operators", "fontStyle": "bold", "pos": 2},
    535: {"name": "Keywords", "fontStyle": "italic", "pos": 2},
    549: {"name": "Variables", "fontStyle": "italic", "pos": 2},
    556: {"name": "Variables", "fontStyle": "italic", "pos": 2},
    563: {"name": "Language variables", "fontStyle": "italic", "pos": 2},
    570: {"name": "Java Variables", "fontStyle": "italic", "pos": 2},
    577: {"name": "Java Imports", "fontStyle": "underline", "pos": 2},
    584: {"name": "Packages", "fontStyle": "underline", "pos": 2},
    591: {"name": "Packages", "fontStyle": "underline", "pos": 2},
    603: {"name": "Functions", "fontStyle": "bold", "pos": 2},
    670: {"name": "Methods", "fontStyle": "italic", "pos": 2},
    691: {
        "name": "Source Js Keyword Operator Delete,source Js Keyword Operator In,source Js Keyword Operator Of,source Js Keyword Operator Instanceof,source Js Keyword Operator New,source Js Keyword Operator Typeof,source Js Keyword Operator Void",
        "fontStyle": "italic",
        "pos": 2,
    },
    740: {"name": "Strings", "fontStyle": "italic", "pos": 2},
    754: {"name": "Constant other symbol", "fontStyle": "underline", "pos": 2},
    #  768: {"name": "Constants", "fontStyle": "underline", "pos": 2},
    #  775: {"name": "Constants", "fontStyle": "underline", "pos": 2},
    819: {"name": "Headings", "fontStyle": "bold", "pos": 2},
    826: {"name": "Headings", "fontStyle": "bold", "pos": 2},
    868: {
        "name": "[VSCODE-CUSTOM] Markdown headings",
        "fontStyle": "bold underline",
        "pos": 2,
    },
    903: {
        "name": "[VSCODE-CUSTOM] Markdown Inline Raw",
        "fontStyle": "italic",
        "pos": 2,
    },
    910: {
        "name": "[VSCODE-CUSTOM] Markdown Inline Raw",
        "fontStyle": "italic",
        "pos": 2,
    },
    951: {
        "name": "[VSCODE-CUSTOM] Markdown Underline Link/Image",
        "fontStyle": "italic",
        "pos": 2,
    },
    958: {
        "name": "[VSCODE-CUSTOM] Markdown Link Title/Description",
        "fontStyle": "italic",
        "pos": 2,
    },
    1014: {"name": "Deprecated", "fontStyle": "strikethrough", "pos": 2},
    1056: {"name": "[VSCODE-CUSTOM] JSON Property Name", "fontStyle": "bold", "pos": 2},
    1196: {"name": "python function decorator @", "fontStyle": "bold", "pos": 2},
    1203: {"name": "python function support", "fontStyle": "bold", "pos": 2},
    1340: {"name": "Import module JS", "fontStyle": "underline", "pos": 2},
    1421: {"name": "js operator.assignment", "fontStyle": "bold", "pos": 2},
    1495: {
        "name": "styling css pseudo-elements/classes to be able to differentiate from classes which are the same colour",
        "fontStyle": "italic",
        "pos": 2,
    },
    1628: {"name": "SQL Variables", "fontStyle": "italic", "pos": 2},
    1710: {"name": "comments", "fontStyle": "bold", "pos": 2},
    1766: {"name": "C++/C#", "fontStyle": "italic bold", "pos": 2},
    1801: {
        "name": "[VSCODE-CUSTOM] Markdown Quote",
        "fontStyle": "underline",
        "pos": 2,
    },
    747: {"name": "Inherited Class", "fontStyle": "underline", "pos": 2},
    1829: {"name": "comment", "fontStyle": "bold", "pos": 0},
    1792: {"name": "Comments", "fontStyle": "bold", "pos": 1},
    795: {
        "name": "Attribute IDs",
        "fontStyle": "italic underline",
        "pos": 1,
    },
    803: {
        "name": "Attribute class",
        "fontStyle": "bold underline",
        "pos": 1,
    },
}
